### ISSUE TITLE
style-local.json in the gh-pages branch reads hillshade and contours from url

### ISSUE THREAD

**Issue by spatialillusions** [openmaptiles/klokantech-terrain-gl-style#9]
The style-local.json in the gh-pages branch reads the hillshade and contours from urls, but the main file from a local mbtiles:

```
  "sources": {
    "openmaptiles": {
      "type": "vector",
      "url": "mbtiles://{v3}"
    },
    "hillshading": {
      "type": "raster",
      "url": "https://klokantech.tilehosting.com/data/hillshades.json?key=tXme5cuqgrCqdPoZHqyn",
      "tileSize": 256
    },
    "contours": {
      "type": "vector",
      "url": "https://klokantech.tilehosting.com/data/contours.json?key=tXme5cuqgrCqdPoZHqyn"
    }
```

I would suggest that this is changed so that all sources in style-local.json are read from local files, like this:
```
  "sources": {
    "openmaptiles": {
      "type": "vector",
      "url": "mbtiles://{v3}"
    },
    "hillshading": {
      "type": "raster",
      "url": "mbtiles://{hillshading}",
      "tileSize": 256
    },
    "contours": {
      "type": "vector",
      "url": "mbtiles://{contours}"
    }
```

And I also think the font path needs to be fixed so that it will read a local font.

**Comment by markuman** [comment]
I try to get also the terrain style working in `tileserver-gl`.

```Dockerfile
RUN mkdir /usr/src/app/node_modules/tileserver-gl-styles/styles/terrain
COPY style.json /usr/src/app/node_modules/tileserver-gl-styles/styles/terrain/
```

It this basically the right way?  
And I also needs (next to my planet.mbtiles file) a contours and hillshading mbtiles file? I like to generate it by myself, but I cannot find any documentation how to do this?  
Any ideas or hints @spatialillusions 

ref: https://github.com/openmaptiles/openmaptiles/issues/931

**Comment by TomPohys** [comment]
Thanks for pointing this out. Fixed in https://github.com/openmaptiles/maptiler-terrain-gl-style/commit/e12f55141dba7f6e8e3057ba44a329573810e583.
